library(av)
library(plotly)
library(htmlwidgets)
library(webshot2)
source(01_simluation_files.R)

### Code here generated by Gemeni

# --- Function to rotate and save video ---
generate_spinning_mp4 <- function(plot_obj, filename, n_frames = 600, fps = 30) {
  
  message(paste("Processing:", filename))
  message(paste("Rendering", n_frames, "frames at", fps, "fps (Duration: 30s)..."))
  
  # Create a temporary directory
  temp_dir <- file.path(tempdir(), "plotly_frames")
  if (!dir.exists(temp_dir)) dir.create(temp_dir)
  
  # Clean up old files
  file.remove(list.files(temp_dir, full.names = TRUE))
  
  # --- CRITICAL CHANGE FOR 2 ROTATIONS ---
  angles <- seq(0, 2*pi, length.out = n_frames)
  radii <- 1.8 
  
  img_files <- character(n_frames)
  
  for (i in seq_along(angles)) {
    angle <- angles[i]
    
    # 1. Update Camera Position
    new_x <- radii * cos(angle)
    new_y <- radii * sin(angle)
    
    p_rotated <- plot_obj %>%
      plotly::layout(scene = list(
        camera = list(
          eye = list(x = new_x, y = new_y, z = 1.25)
        )
      ))
    
    # 2. Define filenames
    html_file <- file.path(temp_dir, "temp_plot.html")
    png_file  <- file.path(temp_dir, sprintf("frame_%03d.png", i))
    
    # 3. Save as HTML first
    htmlwidgets::saveWidget(p_rotated, html_file, selfcontained = FALSE)
    
    # 4. Take screenshot
    # delay is kept short to speed up the 900-frame process
    webshot2::webshot(url = html_file, file = png_file, 
                      vwidth = 1200, vheight = 800, 
                      selector = ".plotly", 
                      delay = 0.1) 
    
    img_files[i] <- png_file
    
    # Optional: Progress counter so you know it's not frozen
    if (i %% 50 == 0) message(paste("Rendered frame", i, "of", n_frames))
  }
  
  # 5. Stitch images into MP4
  av::av_encode_video(input = img_files, output = filename, framerate = fps)
  
  message(paste("Saved video to:", filename))
  
  # Cleanup
  unlink(temp_dir, recursive = TRUE)
}

# --- Execute ---

# Output Directory
output_dir <- "C:/Users/jharmon/Documents/k_anon"

if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

plots_to_process <- list(
  list(plot = p_1, name = "k_anon_scenario_1.mp4"),
  list(plot = p_2, name = "k_anon_scenario_2.mp4"),
  list(plot = p_3, name = "k_anon_scenario_3.mp4"),
  list(plot = p_4, name = "k_anon_scenario_4.mp4")
)

for (item in plots_to_process) {
  tryCatch({
    full_path <- file.path(output_dir, item$name)
    
    # We rely on the defaults (900 frames, 30 fps) set in the function above
    generate_spinning_mp4(item$plot, full_path)
    
  }, error = function(e) {
    message(paste("Error processing", item$name, ":", e$message))
  })
}